# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 05:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSYPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('ctitation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PSYPTDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(blank=True, null=True)),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('psy_pt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PSYPT')),
            ],
        ),
        migrations.CreateModel(
            name='PSYPTFACET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet', models.TextField(blank=True, null=True)),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('psy_pt_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PSYPTDomain')),
            ],
        ),
        migrations.CreateModel(
            name='PSYPTHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PSYPTItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('item_num_1', models.TextField()),
                ('item_num_2', models.TextField(blank=True, null=True)),
                ('item_num_3', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PSYPTItemDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet', models.TextField(blank=True, null=True)),
                ('keyed', models.BooleanField(default=0)),
                ('psy_pt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PSYPT')),
                ('psy_pt_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PSYPTDomain')),
                ('psy_pt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PSYPTItem')),
            ],
        ),
        migrations.CreateModel(
            name='PSYPTResultDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.TextField()),
                ('score_desc', models.TextField(blank=True, null=True)),
                ('psy_pt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PSYPT')),
                ('psy_pt_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PSYPTDomain')),
            ],
        ),
        migrations.AddField(
            model_name='psypthist',
            name='psy_pt_item_def',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PSYPTItemDef'),
        ),
        migrations.AddField(
            model_name='psypthist',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
