# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 06:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_psyptuserattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psypthist',
            name='psy_pt_item_def',
        ),
        migrations.RemoveField(
            model_name='psypthist',
            name='userid',
        ),
        migrations.AddField(
            model_name='psypthist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psypthist',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='psypthist',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='psypthist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psyptuserattempt',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.PSYPTHist'),
            preserve_default=False,
        ),
    ]
