# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170430_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psypthist',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psypthist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
