# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20170430_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='psyptdomain',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
