# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_psyptdomain_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='psypt',
            name='totalquestions',
            field=models.IntegerField(default=20),
        ),
    ]
