# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_psypt_totalquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psyptresultdef',
            name='psy_pt',
        ),
        migrations.AddField(
            model_name='psyptresultdef',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.PSYPTHist'),
            preserve_default=False,
        ),
    ]
