# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_psyptresultdef_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psyptitem',
            name='psy_pt_domain',
        ),
        migrations.AddField(
            model_name='psyptitem',
            name='psy_pt_domain',
            field=models.ManyToManyField(to='mainapp.PSYPTDomain'),
        ),
    ]
