# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20170510_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psyptitem',
            name='keyed',
            field=models.TextField(blank=True, default='+', null=True),
        ),
    ]
